// 🔹 الكود الأصلي بتاعك (محطوط في كومنت عشان تقدر ترجعه في أي وقت)

export const weatherImages = {
  'Partly cloudy': require('@/assets/partly-cloudy.png'),
  'Moderate rain': require('@/assets/heavy-rain.png'),
  'Patchy rain possible': require('@/assets/rain-possible.png'),
  'Patchy rain nearby': require('@/assets/rain-possible.png'),
  'Sunny': require('@/assets/contrast.png'),
  'Clear': require('@/assets/contrast.png'),
  'Overcast': require('@/assets/overCast.png'),
  'Cloudy': require('@/assets/cloudy.png'),
  'Light rain': require('@/assets/lightRain.png'),
  'Moderate rain at times': require('@/assets/heavy-rain.png'),
  'Heavy rain': require('@/assets/heavy-rainnn.png'),
  'Heavy rain at times': require('@/assets/heavy-rainnn.png'),
  'Moderate or heavy freezing rain': require('@/assets/freezing.png'),
  'Moderate or heavy rain with thunder': require('@/assets/thunder.png'),
  'Moderate or heavy rain shower': require('@/assets/lightRain.png'),
  'Moderate or heavy snow showers': require('@/assets/snowy.png'),
  'Mist': require('@/assets/fog.png'),
  'Fog': require('@/assets/fog.png'),
  'other': require('@/assets/contrast.png'),
  'Freezing fog': require('@/assets/freezing.png'),
  'Patchy fog': require('@/assets/yumminky.png'),
  'Light snow': require('@/assets/snowy.png'),
  'Moderate snow': require('@/assets/snowy.png'),
  'Heavy snow': require('@/assets/snowy.png'),
  'Sleet': require('@/assets/sleet.png'),
  'Ice pellets': require('@/assets/freezing.png'),
  'Blowing snow': require('@/assets/snowy.png'),
  'Patchy snow possible': require('@/assets/snowy.png'),
  'Patchy light snow': require('@/assets/snowy.png'),
  'Patchy moderate snow': require('@/assets/snowy.png'),
  'Patchy heavy snow': require('@/assets/snowy.png'),
  'Patchy light rain': require('@/assets/lightRain.png'),
  'Light drizzle': require('@/assets/lightRain.png'),
  'Patchy light drizzle': require('@/assets/lightRain.png'),
  'Patchy moderate rain': require('@/assets/lightRain.png'),
  'Light rain shower': require('@/assets/lightRain.png'),
  'Patchy light rain with thunder': require('@/assets/thunder.png'),
  'Thundery outbreaks possible': require('@/assets/thunder.png'),
  'Torrential rain shower': require('@/assets/thunder.png'),
  'Patchy light snow with thunder': require('@/assets/thunder.png'),
  'Moderate or heavy snow with thunder': require('@/assets/thunder.png'),
  'Patchy freezing drizzle possible': require('@/assets/freezing.png'),
  'Patchy sleet possible': require('@/assets/freezing.png'),
  'Patchy freezing rain possible': require('@/assets/freezing.png'),
  'Moderate or heavy freezing drizzle': require('@/assets/freezing.png'),
  'Tornado': require('@/assets/thunder.png'),
  'Blizzard': require('@/assets/snowy.png'),
  'Cold': require('@/assets/freezing.png'),
  'Hot': require('@/assets/contrast.png'),
  'Windy': require('@/assets/cloudy.png'),
  'default': require('@/assets/contrast.png'),
};
